# main.yml

# 工作流程的名字
name: Build and Release apk

# 工作流程触发的时机，这里是当一个版本标签推送到仓库时触发
on:
  push:
    tags:
      - v*

# 这个工作流程需要执行的任务
jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    # 这个任务的步骤
    steps:
      # 拉取项目代码
      - uses: actions/checkout@v6
      # 建立 java 环境
      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: "19"
      # 建立 Flutter 环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.19.x
      # 下载项目依赖
      - run: flutter pub get
      # 检查清理冗余库
      - run: flutter pub deps --style=compact
      # 打包 APK
      - run: flutter build apk --release --split-per-abi
      # 发布到 Release
      - name: Release apk
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/app/outputs/flutter-apk/*.apk"
